export const GET_CHECK_LIST_REQUEST = 'GET_CHECK_LIST_REQUEST';
export const GET_CHECK_LIST_SUCCESS = 'GET_CHECK_LIST_SUCCESS';
export const GET_CHECK_LIST_FAILURE = 'GET_CHECK_LIST_FAILURE';

export const GET_STOCKS_REQUEST = 'GET_STOCKS_REQUEST';
export const GET_STOCKS_SUCCESS = 'GET_STOCKS_SUCCESS';
export const GET_STOCKS_FAILURE = 'GET_STOCKS_FAILURE';

export const SAVE_ALL_STOCKS_REQUEST = 'SAVE_ALL_STOCKS_REQUEST';
export const SAVE_ALL_STOCKS_SUCCESS = 'SAVE_ALL_STOCKS_SUCCESS';
export const SAVE_ALL_STOCKS_FAILURE = 'SAVE_ALL_STOCKS_FAILURE';

export const SUBMIT_STOCK_REQUEST = 'SUBMIT_STOCK_REQUEST';
export const SUBMIT_STOCK_SUCCESS = 'SUBMIT_STOCK_SUCCESS';
export const SUBMIT_STOCK_FAILURE = 'SUBMIT_STOCK_FAILURE';

export const SAVE_CATEGORIES_REQUEST = 'SAVE_CATEGORIES_REQUEST';
export const SAVE_CATEGORIES_SUCCESS = 'SAVE_CATEGORIES_SUCCESS';
export const SAVE_CATEGORIES_FAILURE = 'SAVE_CATEGORIES_FAILURE';

export const CLEAR_STOCKS = 'CLEAR_STOCKS';

export const RESET_STATUS_STATE = 'RESET_STATUS_STATE';
