export const CAPTURE_REQUEST = 'CAPTURE_REQUEST';
export const CAPTURE_SUCCESS = 'CAPTURE_SUCCESS';
export const CAPTURE_FAILURE = 'CAPTURE_FAILURE';

export const UPDATE_NET_INFO = 'UPDATE_NET_INFO';
export const UPDATE_MODE = 'UPDATE_MODE';

export const SYNC_DATA_REQUEST = 'SYNC_DATA_REQUEST';
export const SYNC_DATA_SUCCESS = 'SYNC_DATA_SUCCESS';
export const SYNC_DATA_DONEALL = 'SYNC_DATA_DONEALL';
export const SYNC_DATA_FAILURE = 'SYNC_DATA_FAILURE';

export const RESET_STATUS_STATE = 'RESET_STATUS_STATE';
