export const UPDATE_AUTHORIZATION = 'UPDATE_AUTHORIZATION';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_DISMISS_ERROR = 'AUTH_DISMISS_ERROR';
export const AUTH_DISMISS_MESSAGE = 'AUTH_DISMISS_MESSAGE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';
export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
